- satis.json
> Add order comment extension

- satis.json
https://github.com/opsway/magento-mod-pipeliner repo
> Add OpsWay_Pipeliner extension

- satis.json
> updated to newer AOEpeople/Aoe_JsCssTstamp.git

- satis.json
See https://github.com/Smile-SA/smile-magento-elasticsearch
> Add Smile Elasticsearch module

- satis.json
> Added Daily Deals extension

- satis.json
Add logicspot/magento_core and logicspot/magento_globalmessage modules
> Add LogicSpot modules

- satis.json
Adds HTML5 input types and some WYSIWYG features to admin forms and product attributes.
> Add Form Elements

- satis.json
https://github.com/Flagbit/Magento-FACTFinder/
so that it can replace the connect20 package then. see as well: https://github.com/Flagbit/Magento-FACTFinder/pull/92
> add flagbit/factfinder

- satis.json
Added husseycoding/ajaxcartpopup
> Added husseycoding/ajaxcartpopup

- satis.json
https://github.com/clockworkgeek/FutureSlider
> Add clockworkgeek/futureslider

- satis.json
vcs for Added aligent feeds module
> Added aligent feeds module

- satis.json
Great module to ajaxify all the things!
See https://github.com/hws47a/VF_EasyAjax
> Added VF_EasyAjax

- satis.json
Please consider this hack to allow magento to use environment variables in the local.xml config.
> Add 'magento-config-envvars'.

- satis.json
I'm maintaining this library. Please contact me if something is unclear
> add swisspost-yellowcube/magento-yellowcube.git

- satis.json
M CE 1.9.2.2 compatibility with PHP 7.
> Added Inchoo_PHP7 extension

- satis.json
Added repository for DiamanteDesk integration
> Added DiamanterDesk extension

- satis.json
Adding: Environment Banner, Config Setup Helper, fixed.io integration, and Remember Admin Settings
> Adding C3 Media extensions

- satis.json
https://github.com/wigman/AjaxSwatches
> add wigman/ajax-swatches

- satis.json
added aligent/missingcustomerfix
> added aligent/missingcustomerfix and aligent/security

- satis.json
- script/initSatisGenerator.php
Ref https://github.com/composer/composer/issues/4963
http://packages.fooman.co.nz/ not updated as it doesn't support SSL currently, followup recommended.
> Update sources to https per required composer changes

- satis.json
added aligent/fleet
(module for fleet)
> added aligent/fleet

- satis.json
See http://www.blackbird.am/ for more info about Blackbird, this extension connects to that, and offers search results from the API.
> Added Blackbird Merlin Magento Extension

- satis.json
This patch adds Magento 1 Slovenian translation module. Thanks for considering merging it to composer-repository.
> Slovenian sl_SI translation module

- satis.json
See: https://www.magentocommerce.com/magento-connect/pay-nl-payment-gateway.html
> Added pay.nl magento plugin

- satis.json
added clockworkgeek/Magento-Guest-Cookies
> added clockworkgeek/Magento-Guest-Cookies

- satis.json
ctn-mage-tools 
Magento Development Tools
> add ctinnita/ctn-mage-tools.git to satis.json

- satis.json
> Add Magehack_Autogrid version 1.0.0

- satis.json
Now full compiled in its own repository with own modman
> Add Mzax_Emarketing

- satis.json
added Fat Zebra payment extension
> added Fat Zebra payment extension

- satis.json
Looks like @zainengineer added a duplicate of an existing line
> Removed duplicate from the pull request #416

- satis.json
No longer listed on Magento Connect
> Added Ebizmarts SagePay OFFICIAL Extension for Magento (free)

- satis.json
The guys now a https certificate, so lets use it :)
> Use https for fooman.co.nz

- satis.json
Connect is lagging behind the developers current release
> Added FishPig Magento 1 WordPress integration plugin

- satis.json
Add customergroup_paymentmethods package
> :package: Add customergroup_paymentmethods

- satis.json
Add yuzu-co/magento on satis.json
> Add yuzu-co/magento

- satis.json
I fixed the error when you download connect20/yotporeviews
Not Found
The requested URL /git@github.com:proxium/yotporeviews.git was not found on this server.
> Add connect20/yotporeviews

- satis.json
Adding Metrilo plugin extension to the list of repositories.
> Add Metrilo Extension
